version: '3'

services:
  app:
    image: nikosp98/backend-niko:backend-niko
    container_name: niko98-backend-extra-app
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always
